Add line breaks to abstract text
GeoscienceAustralia/dea-config pull request #1013
Opened 2022-01-24 01:55 UTC by erin-telfer

Attempting to fix the line break formatting on abstract text by adding "\n"

2022-01-24 05:57 UTC, pindge requested changes

2022-01-24 05:57 UTC, pindge commented on dev/services/wms/ows_refactored/inland_water/wofs/annual/ows_wofs_annual_cfg.py
> +- Wet Count: how many times water was detected in observations that were clea
clea? is this a typo??

2022-01-24 05:57 UTC, erin-telfer commented on dev/services/wms/ows_refactored/inland_water/wofs/annual/ows_wofs_annual_cfg.py
> +- Wet Count: how many times water was detected in observations that were clea
defs typo. fixing now.

2022-01-25 00:24 UTC, pindge approved these changes

2022-01-25 00:42 UTC, merged