Add experimental (RGB bands only) S2/LS combined layer to prod.
GeoscienceAustralia/dea-config pull request #1137
Opened 2023-01-29 23:25 UTC by SpacemanPaul

Prototype S2/LS combined layer, currently restricted to visible bands only (RGB) due a lack of common band aliases for the mappable infrared bands.

Added to dev in #1134.

Note I have NOT added the new prod layer to the Terria catalog.  This is still an experimental layer - testing on the prod database because S2C3 data in dev is still very patchy.

2023-01-30 04:50 UTC, pindge requested changes

2023-01-30 04:50 UTC, pindge commented on prod/services/wms/inventory.json
> +    "total_layers_count": 69,
its only adding `1` layer, the count should be `64` + `1` = 65

2023-01-31 01:59 UTC, robbibt approved these changes
This looks great to me @SpacemanPaul in terms of band names, descriptions, naming etc - will review the WMS itself in more detail once it's live in OWS (e.g. compare it directly against the existing GSKY layer)

2023-01-31 02:16 UTC, robbibt commented on prod/services/wms/inventory.json
> +    "total_layers_count": 69,
This looks like it has been fixed

2023-01-31 03:17 UTC, merged