ABARES Catchment Land Use Map 2023 - prod description and metadata
GeoscienceAustralia/dea-config pull request #1272
Opened 2024-06-13 00:36 UTC by erialC-P

This PR includes a product description and stac metadata index to support indexing of the 2023 ABARES CLUM dataset into the prod and dev databases.

There is a new product folder under `GeoscienceAustralia/dea-config/products/others/` titled `abares_clum_2023`. Its contents include:
- an odc-product.yaml
- a stac-item.json
- a thumbnail.jpg
- updated readme.md documenting the process used to generate the above files.

Thanks for the reviews. Happy to make updates if required

2024-06-19 05:55 UTC, omad requested changes
Thanks, this looks like a great start. There's a few things I think should be fixed before we merge/upload/publish this..

Cheers

2024-06-19 05:55 UTC, omad commented on products/others/abares_clum_2023/README.md
> +# ABARES Catchment scale land use of Australia - Update December 2024
```suggestion
# ABARES Catchment scale land use of Australia - Update December 2023
```
Typo fix.

2024-06-19 05:55 UTC, omad commented on products/others/abares_clum_2023/README.md
> +> Land use: ABARES 2024, Catchment Scale Land Use of Australia – Update December 2023, Australian Bureau of Agricultural and Resource Economics and Sciences, Canberra, February, CC BY 4.0, DOI: 10.25
```suggestion
> Land use: ABARES 2023, Catchment Scale Land Use of Australia – Update December 2023, Australian Bureau of Agricultural and Resource Economics and Sciences, Canberra, February, CC BY 4.0, DOI: 10.25814/2w2p-ph98

```
Typo fix.

2024-06-19 05:55 UTC, omad commented on products/others/abares_clum_2023/abares_clum_2023.stac-item.json
> +      "href":"https://dea-public-data-dev.s3-ap-southeast-2.amazonaws.com/abares_clum_2023/clum_50m_2023.tiff",
```suggestion
      "href":"clum_50m_2023.tiff",
```
This is better as a relative URL, to simplify downloading or moving the dataset around.

2024-06-19 05:55 UTC, omad commented on products/others/abares_clum_2023/abares_clum_2023.stac-item.json
> +    },
```suggestion

```
STAC Items don't strictly require a `self` URL. It's a nice to have, but mostly makes sense for API responses. When writing to static files it's often more trouble than it's worth, since if they're ever moved they'll be wrong.

2024-06-19 06:22 UTC, erialC-P commented on products/others/abares_clum_2023/README.md
> +> Land use: ABARES 2024, Catchment Scale Land Use of Australia – Update December 2023, Australian Bureau of Agricultural and Resource Economics and Sciences, Canberra, February, CC BY 4.0, DOI: 10.25
Good catch but the official citation attached to the DOI dates as 2024 as the dataset was released in about February this year

2024-06-19 06:23 UTC, erialC-P commented on products/others/abares_clum_2023/abares_clum_2023.stac-item.json
> +    },
Thanks, that's good to know! :)

2024-06-19 06:24 UTC, erialC-P commented on products/others/abares_clum_2023/abares_clum_2023.stac-item.json
> +      "href":"https://dea-public-data-dev.s3-ap-southeast-2.amazonaws.com/abares_clum_2023/clum_50m_2023.tiff",
Awesome, thank-you!

2024-06-19 06:27 UTC, erialC-P commented
Thanks for the review @omad 
I've committed those changes (and learnt some useful things!) and I think this PR is ready to review/merge again?
The only comment that I left unchanged was a suggested edit to the dataset citation. To keep it aligned with the DOI citation, I left the publication year unchanged.

2024-06-19 07:34 UTC, robbibt commented on products/others/abares_clum_2023/abares_clum_2023.stac-item.json
> +    },
Super neat - we can use this metadata as a nice and simpler template going forward then!

2024-07-04 05:45 UTC, omad approved these changes
I think that looks good now, thanks Claire!

It's uploaded to the [DEA public data bucket](https://data.dea.ga.gov.au/?prefix=projects/abares_clum_2023/), and [indexed and available in the dev environment](https://explorer.dev.dea.ga.gov.au/products/abares_clum_2023/datasets/21489af0-abbe-54ac-9eb5-89bbcba53a57).

I'll index it in DEA Prod once we've checked it's okay in Dev.

2024-07-08 01:43 UTC, omad commented
This is now published
- In the public data bucket
- In the DEA Production ODC Index
- In the DEA Development ODC Index

2024-07-08 01:43 UTC, merged