Fix spelling of Tasseled, so consistent. And multiple changes to the data description. The same changes have been made to CMI.
GeoscienceAustralia/dea-config pull request #625
Opened 2020-11-29 23:24 UTC by vnewey

2020-11-29 23:30 UTC, pindge approved these changes
Good

2020-11-29 23:31 UTC, pindge requested changes

2020-11-29 23:31 UTC, pindge commented on dev/services/wms/ows/ows_cfg.py
> +The ability to map partial inundation is also crucial to understand patterns of human water use. We need to be able to identify potential wetlands and groundwater dependent ecosystems on the Australi
was there suppose to be a fullstop here? @vnewey

2020-11-29 23:32 UTC, pindge commented on dev/services/wms/ows/ows_cfg.py
> +vegetated wetlands, salt flats, salt lakes, coastal land cover classes
if not dot points? should they be inline with the above line?

2020-11-29 23:36 UTC, vnewey commented on dev/services/wms/ows/ows_cfg.py
> +vegetated wetlands, salt flats, salt lakes, coastal land cover classes
The dot points all appeared on the same line.  Do you know how to make them appear as dot points?

2020-11-30 00:01 UTC, pindge commented on dev/services/wms/ows/ows_cfg.py
> +vegetated wetlands, salt flats, salt lakes, coastal land cover classes
```

 - vegetated wetlands,
 - salt flats,
 - salt lakes,
 - coastal land cover classes
```

![image](https://user-images.githubusercontent.com/24644475/100557171-681f6480-32fb-11eb-88a5-d4d28e1c9d8b.png)

2020-12-02 02:43 UTC, pindge approved these changes

2020-12-02 02:46 UTC, merged