draft c3_ows
GeoscienceAustralia/dea-config pull request #641
Opened 2021-01-18 22:47 UTC by pindge

For paul's visibility.

2021-01-18 23:00 UTC, whatnick requested changes
We should aim for a single, refactored ows_cfg object. With subsets of layers created in separate python files with the existing ows_cfg aggregating them.

2021-01-18 23:04 UTC, pindge commented on dev/services/wms/ows/c3_ows_cfg.py
> +ows_cfg = {
@SpacemanPaul , is now the perfect opportunity to build ows with fragmented ows_cfg files?

2021-01-19 06:15 UTC, pindge commented on dev/services/wms/ows/c3_ows_cfg.py
> +            #     "flags": {"or": {"wet": True, "sea": True}},
@GypsyBojangles I need some advice on what to do with `sea` flag

2021-01-19 06:15 UTC, pindge commented on dev/services/wms/ows/c3_ows_cfg.py
> +                # "sea": False,
@GypsyBojangles this fc style with `pq_masks` enabled doesn't show dense green anymore, which looks very similar to fc_albers, i will need to look at the coastal areas to see how much impact it is without `sea` flag

2021-01-21 05:09 UTC, GypsyBojangles commented on dev/services/wms/ows/c3_ows_cfg.py
> +            #     "flags": {"or": {"wet": True, "sea": True}},
To summarize our conversation with Team X:
- When we replace the old flag "terrain_or_low_angle", we should replace with both "low_solar_angle" and "terrain_shadow". Lets start by assumign that these are both set to whatever terrain_or_low_angle was
- For masking the sea bit away, use Fractional Cover Percentiles as a base:
                    "flags": {
                        "band": "land",
                        "product": "geodata_coast_100k",
                        "ignore_time": True,
                        "ignore_info_flags": [],
                    },

2021-03-01 05:35 UTC, pindge commented
Merged in through refactor

2021-03-01 05:35 UTC, closed without merging