tidy wetlands tool sections
GeoscienceAustralia/dea-config pull request #643
Opened 2021-01-19 23:21 UTC by BexDunn

move wetlands insight tool sections into a group

2021-01-19 23:24 UTC, pindge commented
has this been tested?

2021-01-19 23:27 UTC, pindge requested changes

2021-01-19 23:27 UTC, pindge commented on dev/terria/dea.json
> +	        {
please align the brackets

2021-01-19 23:53 UTC, BexDunn commented on dev/terria/dea.json
> +	        {
oh no! I missed one :( I was trying. Yes, it has been tested using an online JSON parser + pycharm. Is that ok? I'll fix the brackets now

2021-01-19 23:54 UTC, pindge commented on dev/terria/dea.json
> +	        {
not exactly the testing I am thinking of, i can test it for u.

2021-01-19 23:58 UTC, pindge commented
@BexDunn 
![image](https://user-images.githubusercontent.com/24644475/105108447-580f4e80-5b0e-11eb-8c18-c490a903f9de.png)

2021-01-20 23:30 UTC, BexDunn commented on dev/terria/dea.json
> +	        {
Thanks for teaching me how to test this. I have tested the tidied up file on terria and it should be good to go @pindge ?

2021-01-21 04:01 UTC, pindge requested changes

2021-01-21 04:01 UTC, pindge commented on dev/terria/dea.json
> +	        {
everything else looks good, but this starting `{` is not aligned with the above

2021-01-21 04:02 UTC, pindge requested changes

2021-01-21 04:02 UTC, pindge commented on dev/terria/dea.json
> +               "name": "DEA Wetlands Insight Tool",
now i look closely, this line `name` isn't aligned with the rest, please double check

2021-01-21 04:28 UTC, pindge approved these changes

2021-01-21 04:28 UTC, merged