add underscore to layername
GeoscienceAustralia/dea-config pull request #667
Opened 2021-02-17 00:58 UTC by pindge

- add an underscore to layer names for consistency

2021-02-17 01:19 UTC, GypsyBojangles approved these changes

2021-02-17 01:21 UTC, GypsyBojangles requested changes
You need to change the linked WCS coverage name too. Has dea.json been updated already?

2021-02-17 01:26 UTC, pindge commented
> You need to change the linked WCS coverage name too. Has dea.json been updated already?

wrong file

2021-02-17 01:27 UTC, pindge commented
> You need to change the linked WCS coverage name too. Has dea.json been updated already?

ok, fixed, change this round is to dev only, so only to `dea.json`

2021-04-09 05:02 UTC, GypsyBojangles approved these changes

2021-08-16 00:39 UTC, closed without merging