for pauls visibility
GeoscienceAustralia/dea-config pull request #670
Opened 2021-02-19 02:17 UTC by pindge

2021-02-19 02:28 UTC, pindge commented
```
ows_1  | [2021-02-19 02:25:40,075] datacube_ows.ows_configuration [None] [ERROR] Could not load layer Collection 3 Water: Unknown band name/alias: pq_masks in layer ga_ls_wo_3
```

2021-02-23 04:07 UTC, SpacemanPaul requested changes
See comment.

2021-02-23 04:07 UTC, SpacemanPaul commented on dev/services/wms/ows_refactored/wofs/ows_c3_wo_cfg.py
> +        {
duplicate entry here.

2021-02-23 04:10 UTC, SpacemanPaul approved these changes

2021-02-23 04:12 UTC, merged