add more clarity to wofs groups
GeoscienceAustralia/dea-config pull request #673
Opened 2021-02-24 06:01 UTC by pindge

- add clarity to wofs grouped layers

2021-02-24 08:59 UTC, alexgleith requested changes

2021-02-24 08:59 UTC, alexgleith commented on dev/services/wms/ows_refactored/wofs/ows_wofs_annual_cfg.py
> +    "title": "Water Observations from Space annual statistics",
Please keep consistent case

2021-02-24 08:59 UTC, alexgleith commented on dev/services/wms/ows_refactored/wofs/ows_wofs_seasonal_cfg.py
> +    "title": "Water Observations from Space Seasonal",
This is Capital

2021-02-24 08:59 UTC, alexgleith commented on dev/services/wms/ows_refactored/wofs/ows_wofs_summary_cfg.py
> +    "title": "Water Observations from Space summary statistics",
This is not

2021-02-24 22:34 UTC, pindge commented on dev/services/wms/ows_refactored/wofs/ows_wofs_seasonal_cfg.py
> +    "title": "Water Observations from Space Seasonal",
@erin-telfer , is this `Seasonal Statistics` or just `Seasonal`, asking for clarification ,

2021-02-26 04:35 UTC, erin-telfer commented on dev/services/wms/ows_refactored/wofs/ows_wofs_annual_cfg.py
> +    "title": "Water Observations from Space annual statistics",
"title": "Water Observations from Space Annual Statistics",

2021-02-26 05:16 UTC, erin-telfer commented on dev/services/wms/ows_refactored/wofs/ows_wofs_seasonal_cfg.py
> +    "title": "Water Observations from Space Seasonal",
It shouldn't be either.

2021-02-26 10:14 UTC, SpacemanPaul approved these changes
Looks fine to me.

2021-02-28 21:15 UTC, merged