add yamllint
GeoscienceAustralia/dea-config pull request #761
Opened 2021-06-07 23:27 UTC by pindge

- add yamllint action
- remove tab

2021-06-08 05:00 UTC, omad requested changes

2021-06-08 05:00 UTC, omad commented on .github/workflows/yaml_linting.yaml
> +          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```suggestion

```
This shouldn't need any secrets or tokens.

2021-06-10 01:57 UTC, pindge commented on .github/workflows/yaml_linting.yaml
> +          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Its useful to highlight the bad bit in the yaml.

2021-06-10 02:30 UTC, omad commented on .github/workflows/yaml_linting.yaml
> +          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Oh okay, this action can also post a comment on a PR, I didn't realise that.

2021-06-10 02:30 UTC, omad approved these changes

2021-06-10 02:30 UTC, merged