Landcover ows
GeoscienceAustralia/dea-config pull request #772
Opened 2021-06-20 23:41 UTC by bellemae

- basic landcover ows config
- add landcover styles to inventory.json
- add config layers to ows root config

2021-06-20 23:49 UTC, pindge requested changes

2021-06-20 23:49 UTC, pindge commented on dev/services/wms/inventory.json
> +                "level4",
json is very rigid, no ending with `,` if this the last item in the list

2021-06-20 23:52 UTC, pindge requested changes

2021-06-20 23:52 UTC, pindge commented on dev/services/wms/ows_refactored/landcover/ows_c2_lc_cyear_cfg.py
> +            {'title': "Water", 'abstract': "", 'values': [220], 'color': '#4D9FDC', 'alpha': 1}]}}
would make it easier to read. if the `]}}` is pushed down to match the level as its opening brackets

2021-06-21 03:40 UTC, bellemae commented on dev/services/wms/inventory.json
> +                "level4",
ooh good spotting! Have now removed these.

2021-06-21 04:10 UTC, merged