Added progressive cache control to all products.
GeoscienceAustralia/dea-config pull request #804
Opened 2021-07-30 05:29 UTC by SpacemanPaul

Progressive cache control is awesome.  We should be progressive cache controlling all the things.

2021-07-30 06:12 UTC, pindge commented
This pr is killing https://github.com/GeoscienceAustralia/dea-config/blob/master/dev/services/wms/ows_refactored/dev_only/ows_hap_cfg.py 
```
{'values_changed': {"root['total_layers_count']": {'new_value': 83, 'old_value': 84}}, 'iterable_item_removed': {"root['layers'][44]": {'product': ['historical_airborne_photography'], 'styles_count': 1, 'styles_list': ['simple_gray']}}}
```

2021-08-02 00:59 UTC, pindge commented
This is the error:

```
 [2021-08-02 00:59:10,849] datacube_ows.ows_configuration [None] [ERROR] Could not parse layer: Dataset cache rule min_datasets value exceeds the max_datasets limit in layer historical_airborne_photography.
```

2021-08-02 01:00 UTC, pindge requested changes

2021-08-02 01:00 UTC, pindge commented on dev/services/wms/ows_refactored/ows_reslim_cfg.py
> +        "min_datasets": 9,
this must be a typo, it should be `max_datasets`

2021-08-04 02:01 UTC, SpacemanPaul commented on dev/services/wms/ows_refactored/ows_reslim_cfg.py
> +        "min_datasets": 9,
Actually no, in the cache rules it is "min_datasets".

2021-08-04 02:02 UTC, SpacemanPaul commented on dev/services/wms/ows_refactored/ows_reslim_cfg.py
> +        "min_datasets": 9,
You're not far off the problem though.

2021-08-04 02:26 UTC, pindge approved these changes

2021-08-04 02:40 UTC, merged