Erin burntarea
GeoscienceAustralia/dea-config pull request #831
Opened 2021-09-09 04:10 UTC by erin-telfer

2021-09-09 04:59 UTC, pindge requested changes

2021-09-09 04:59 UTC, pindge commented on dev/services/wms/ows_refactored/burntarea/ows_provisional_ba_cfg.py
> +                "default_bands": [
the items here are suppose to be `bands` not styles

2021-09-09 04:59 UTC, pindge commented on dev/services/wms/ows_refactored/burntarea/ows_provisional_ba_cfg.py
> +        "url": "", },
can we push this closing `},` to the new line so its more readable?

2021-09-09 04:59 UTC, pindge commented on dev/services/wms/ows_refactored/burntarea/ows_provisional_ba_cfg.py
> +    "mpl_ramp": "PuOr",  # need to ask how to reverse colour ramp
add  `_r` to the end wil be reverse, be careful not to have any space

2021-09-12 22:29 UTC, pindge commented
@erin-telfer you also need to update inventory json https://github.com/GeoscienceAustralia/dea-config/blob/master/dev/services/wms/inventory.json

and ows_root_cfg.py https://github.com/GeoscienceAustralia/dea-config/blob/master/dev/services/wms/ows_refactored/ows_root_cfg.py

2021-09-12 22:33 UTC, erin-telfer commented on dev/services/wms/ows_refactored/burntarea/ows_provisional_ba_cfg.py
> +    "mpl_ramp": "PuOr",  # need to ask how to reverse colour ramp
To clarify, this is the correct text?
"mpl_ramp": "PuOr_r",

2021-09-12 23:11 UTC, pindge requested changes

2021-09-12 23:11 UTC, pindge commented on dev/services/wms/inventory.json
> +        },
json doesnt like trailin `,` at the end

2021-09-12 23:11 UTC, pindge commented on dev/services/wms/inventory.json
> +                "style_dndvi",
so is this `,`

2021-09-13 01:00 UTC, erin-telfer reviewed
-done

2021-09-13 01:04 UTC, pindge approved these changes

2021-09-13 01:13 UTC, merged