Create the last two WOfS summary config files
GeoscienceAustralia/dea-config pull request #875
Opened 2021-10-01 01:05 UTC by supermarkion

Add the last two WO summary config files:

1. ga_ls_wo_fq_fyear_3
2. ga_ls_wo_fq_myear_3

2021-10-04 21:43 UTC, GypsyBojangles commented
Doesn't ga_ls_wo_fq_myear_3 use a different summary plugin?

2021-10-04 22:03 UTC, GypsyBojangles requested changes
Isn't ga_ls_wo_fq_myear_3 a completely different statistic plugin?

2021-10-04 22:40 UTC, supermarkion commented
> Isn't ga_ls_wo_fq_myear_3 a completely different statistic plugin?

You are right. Just fix it: https://github.com/GeoscienceAustralia/dea-config/pull/875/commits/0300ce80cc76f5808559de02320ba9be9aa546ca

2021-10-05 00:04 UTC, GypsyBojangles approved these changes

2021-10-05 00:05 UTC, merged